# Generated by Django 4.2.7 on 2025-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('paypal', 'paypal')], max_length=20),
        ),
    ]
